### ISSUE TITLE
Feature request: request timeout option

### ISSUE THREAD

**Issue by emgfc** [7even/vkontakte_api#60]
Клиент может огромное время ждать ответ на запрос, хотелось бы иметь возможность установить таймаут. В Faraday давно убрали возможность передать некоторые параметры при инициализации соединения (они оставили что-то похожее, но в любом случае провернуть это с данным клиентом не получается), так что единственный верный способ сейчас установить таймауты — это в блоке инициализации соединения.

**Comment by Fedcomp** [comment]
Почему закрыто? нужны таймауты, кто то уже нашел решение?

**Comment by emgfc** [comment]
Закрыто потому, что таймаут сделать можно, *но благодаря прекрасной документации faraday это слегка неочевидно*.

Вот код:
``` ruby
VkontakteApi.configure do |c|
  c.faraday_options = {request: {timeout: 5}}
end
```

**Comment by Jonik19** [comment]
@emgfc спасибо, только сделал свою версию ) https://github.com/Jonik19/vkontakte_api/tree/faraday-timeout
