### ISSUE TITLE
Загрузка фото из S3

### ISSUE THREAD

**Issue by meliborn** [7even/vkontakte_api#69]
Возможно ли? Что передавать в VkontakteApi.upload в параметре ```photo```?  Обычный урл не подходит http://s3.eu-central-1.amazonaws.com/example/photos/images/000/876/114/original/667f423c66.jpg

**Comment by 7even** [comment]
Насколько мне известно, загрузка фото работает только через загрузку самого файла в API - вот [описание параметров](https://vk.com/dev/upload_files), а [вот](https://github.com/7even/vkontakte_api#Загрузка-файлов) как это можно сделать в `vkontakte_api`. Соответственно, файл нужно скачать из S3 и потом загрузить на vk.
