### ISSUE TITLE
NoMethodError: undefined method `b' for nil:NilClass

### ISSUE THREAD

**Issue by stopanko** [7even/vkontakte_api#70]
Вот такая вот штука. -(( 
upload_url = @vk.photos.get_wall_upload_server(group_id: 78348415, access_token: access_token).upload_url
I, [2015-10-10T12:26:22.568994 #26978]  INFO -- : {:method=>"photos.getWallUploadServer", :params=>"access_token=c32086257ebe95227dfefd18c378f3992773e035c6606991017178d68a80bba80710d01e3d8fac4472fe1bb971e24&group_id=78348415"}
E, [2015-10-10T12:26:22.797936 #26978] ERROR -- : #<NoMethodError: undefined method `b' for nil:NilClass>
NoMethodError: undefined method `b' for nil:NilClass
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/cgi/util.rb:18:in `unescape'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/bundler/gems/vk-ruby-b8f51956c91b/lib/vk-ruby/middlewares/vk_logger.rb:41:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/vkontakte_api-1.4.2/lib/vkontakte_api/api.rb:18:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/vkontakte_api-1.4.2/lib/vkontakte_api/method.rb:13:in `call'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/vkontakte_api-1.4.2/lib/vkontakte_api/resolver.rb:20:in `call_method'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/vkontakte_api-1.4.2/lib/vkontakte_api/namespace.rb:12:in `method_missing'
	from (irb):7
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
	from /var/www/moscoweveryday.com/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.1.0 :008 >

**Comment by 7even** [comment]
1. Судя по стек-трейсу ошибки, ее вызывает гем `vk-ruby`, а не `vkontakte_api`. Попробовал тот же вызов у себя - все работает, возвращается урл для загрузки.
2. Не нужно передавать параметр `access_token` - просто `@vk.photos.get_wall_upload_server(group_id: 78348415)`
3. Пользуйтесь fenced code blocks из [GFM](https://help.github.com/articles/github-flavored-markdown/).
