### ISSUE TITLE
Unknown method passed Загрузка файлов

### ISSUE THREAD

**Issue by Stormcore** [7even/vkontakte_api#71]
При попытке загрузки файла 
@vk.upload(url: upload_url, photo: [file_path, 'image/jpeg'])

VKontakte returned an error 3: 'Unknown method passed' after calling method 'upload' with parameters {"photo"=>"././public/images/79101.jpg,image/jpeg", "url"=>"http://cs625324.vk.com/upload.php?act=do_add&amp;mid=123092886&amp;aid=-14&amp;gid=-101666480&amp;hash=bc00851a9c3a57770622c6d94ed044fa&amp;rhash=ccb4c6b8600439c8c7ec684d8553c9a2&amp;swfupload=1&amp;api=1&amp;wallphoto=1"}.

**Comment by 7even** [comment]
Загрузка производится методом `VkontakteApi.upload`.

**Comment by Stormcore** [comment]
Спасибо, помогло, только совсем непонятно, почему нельзя было использовать уже инстанциированный @vk = VkontakteApi::Client.new('***')
