### ISSUE TITLE
Уберите строгие зависимости гемов

### ISSUE THREAD

**Issue by madmike** [7even/vkontakte_api#79]
Нет смысла указывать такие строгие зависимости от других гемов. У меня не получается сделать bundle install из-за конфликтов версий.

**Comment by 7even** [comment]
С какими конкретно гемами возникают проблемы?

**Comment by madmike** [comment]
Конкретно faraday и faraday_middleware. Если оставить хотя бы два уровня версии - то должно быть все ок. Я сделал форк и написал:
      faraday (>= 0.9)
      faraday_middleware (>= 0.9)
Думаю что и в таком случае ничего критичного для этого гема не должно произойти.

В любом случае спасибо за этот удобный инструмент.
Хорошо бы вообще сделать общий гем для работы со всеми известными популярными соц. сетями, нет мыслей по этому поводу?

**Comment by 7even** [comment]
Текущая версия `faraday` - `0.9.2`, `faraday_middleware` - `0.10.0`. Так как `vkontakte_api` необходим `faraday` не меньше `0.9` и `faraday_middleware` не меньше `0.9.1`, просто поменял `~>` на `>=`, это позволит использовать более новые версии.

Пока можно попробовать подключить гем прямо с гитхаба.

**Comment by madmike** [comment]
Все супер, спасибо!
