### ISSUE TITLE
Как посылать сообщения в сообщества? 

### ISSUE THREAD

**Issue by AndreiMotinga** [7even/vkontakte_api#80]
Можно ли с помощью этого gem отправлять сообщение в сообщество, в опеределенный топик, и если да, то как?

**Comment by 7even** [comment]
Все методы API описаны в [официальной документации](https://new.vk.com/dev/methods). Видимо, тут нужен метод [board.createComment](https://new.vk.com/dev/board.createComment).

**Comment by AndreiMotinga** [comment]
7even, я понимаю какой метод нужен, я не совсем понимаю как его использовать. Как произвести авторизацию

**Comment by 7even** [comment]
@AndreiMotinga этот метод требует авторизацию через Implicit Flow, не предназначенный для запросов с сервера.

Если стоит задача отправлять сообщения от имени одного и того же юзера, то теоретически можно попробовать один раз получить токен через [Implicit flow](https://github.com/7even/vkontakte_api#Клиентское-приложение), передав в `:scope` параметр `:offline`; сохранить полученный токен где-то на сервере и делать запросы с ним (`VkontakteApi::Client.new(token)`), но не уверен что это соответствует правилам использования API.
