### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by saroar** [7even/vkontakte_api#81]
is it working with rails 5 ?

**Comment by 7even** [comment]
`vkontakte_api` doesn't depend on any frameworks. I'm pretty sure it works with rails 5 but I haven't tried.

Feel free to reopen this issue if you find any bugs.

**Comment by saroar** [comment]
thanks can you update your rails demo app and update in heroku please it was some bug after sing in 
thanks advance

**Comment by 7even** [comment]
The demo app needs to be rewritten because VK doesn't allow calling `newsfeed.get` from sites ([more info here](https://github.com/7even/vkontakte_api/issues/11)).
