### ISSUE TITLE
Ограничение запросов в секунду

### ISSUE THREAD

**Issue by Vermuth** [7even/vkontakte_api#82]
Вечер добрый!
 У вк есть ограничения на количества запросов в секунду (не более 3х), при использование токена пользователя .  Можно ли сразу для всех запросов использующих токен указывать -время между следующим запросом?
Спасибо

**Comment by 7even** [comment]
Если речь про минимальное время между запросами, то это несложно сделать и в приложении через элементарный `sleep`. `vkontakte_api` предназначен для упрощения HTTP-запросов к API; а когда делать эти запросы - уже дело приложения.
