### ISSUE TITLE
Working with VK stored procedures

### ISSUE THREAD

**Issue by leemour** [7even/vkontakte_api#83]
I couldn't find a way to use stored procedures described here - https://vk.com/dev/execute
Now I'm using `VkontakteApi::API.call("execute.<my_procedure>")` which isn't very sweet.
Could you add this functionality or I'm happy to create PR if you give me some pointers?

**Comment by 7even** [comment]
Actually it is supported since ec9c1127653e7365b04f086112a1f5a3979fefbc. You can use it like this:

``` ruby
vk.execute.procedure_name(procedure_args)
```

**Comment by leemour** [comment]
Silly me. Thanks!

**Comment by tenseisan** [comment]
Hi, can anyone show an example how to work with execute method and mutiple args?
