### ISSUE TITLE
Возвращаемые значения в методе wall.get

### ISSUE THREAD

**Issue by bragovo** [7even/vkontakte_api#86]
Судя по документации https://vk.com/dev/wall.get
Метод должен вернуть объект, в котором первый атрибут количество записей, второй items массив объектов. Сейчас мне гем возвращает массив в котором первым элементов идем количество записей, а далее вторым-третьим и т.д. каждая запись отдельно. В итоге у меня сейчас получается что-то типа:
```
wall[1..-1].each
```
Это так и должно быть или все таки где-то тут есть ошибка?

**Comment by 7even** [comment]
@bragovo судя по всему, это старая версия API. Если указать последнюю версию (`vk.wall.get(owner_id: -86529522, v: 5.64)`), то возвращает в виде объекта с атрибутами `count` и `items`.
