### ISSUE TITLE
Поведение groups.get в test и development environment

### ISSUE THREAD

**Issue by rkotov93** [7even/vkontakte_api#88]
Привет,

Столкнулся со следующей проблемой:

В development environment запрос
```ruby
client.groups.get(filter: 'admin', extended: true, fields: [:name, :photo_200])
```
возвращает массив вида
```ruby
[2, #<Hashie::Mash ...>, #<Hashie::Mash ...>]
```
а в test environment
```ruby
#<Hashie::Mash count=2 items=#<Hashie::Array [#<Hashie::Mash ...>, #<Hashie::Mash ...>]>>
```

**Comment by 7even** [comment]
Вся разница между development и test зависит от того, как VkontakteApi сконфигурирован в приложении (`VkontakteApi.configure`); сам гем не знает, в какой среде он запущен.

Вообще с виду похоже, что запросы идут к разным [версиям API](https://vk.com/dev/versions); есть смысл указать в конфигурации конкретную версию (`config.api_version = '5.65'`, например), и тогда все запросы будут возвращать однотипные результаты.

**Comment by rkotov93** [comment]
Точно, указание версии API помогло. Спасибо!
