### ISSUE TITLE
:facepalm:

### ISSUE THREAD

**Issue by zzet** [7even/vkontakte_api#91]
https://github.com/7even/vkontakte_api/blob/bb7bb6d434ff20800650eb2cb44239ec33e87f32/lib/vkontakte_api/resolver.rb#L28 🤦‍♂️ 

https://www.youtube.com/watch?v=FeCXooh8AXE

**Comment by 7even** [comment]
Если очень хочется динамически вызывать методы, есть `public_send` и даже `__send__`. А обычный `send` здесь должен обрабатываться через `method_missing`, чтобы давать возможность обращаться к API-методам вроде [messages.send](https://vk.com/dev/messages.send).

Возможно, лучшим решением было бы наследовать все Resolvable объекты не от `Object`, а от `BasicObject`.
